# Assessment of Learning {.unnumbered}

Assessment of learning will include a Practicum Proposal, the design and implementation of lesson plans, and reflective practice assignments (discussions and final paper).

Experiential learning integrates scholarly research and prior learning with practical experience in the practicum setting. All work submitted should reflect scholarly thinking and reflective practice, and should incorporate scholarly work with proper citations. APA format is required.

### Assessment Summary {.unnumbered}

| UNIT                                                  | LEARNING ASSESSMENT                     | VALUE |
|-------------------------------------------------------|-----------------------------------------|-------|
| Pre-Work                                              | Practicum Proposal                      | 10%   |
| Unit 1: Developing a Reflective Practice              | Reflective Practice Discussions: 1,2    | 10%   |
| Unit 2: Classroom Observation                         | Reflective Practice Discussions: 3,4    | 10%   |
| Unit 3: Designing Learning Experiences (Lesson Plans) |                                         |       |
| Lesson Plan 1: Authentic and Inclusive Learning       | Lesson Plan 1                           | 10%   |
| Lesson Plan 2: Cross-Cultural Competency              | Lesson Plan 2                           | 10%   |
| Lesson Plan 3: Critical and Creative Thinking         | Lesson Plan 3                           | 10%   |
| Lesson Plan Peer Review                               | Reflective Practice Discussions: 5,6,7  | 10%   |
| Unit 4: Teaching/Facilitating                         | Reflective Practice Discussions: 8,9,10 | 15%   |
| Unit 5: Summative Reflective Practice                 | Reflective Practice Practicum Portfolio | 15%   |

## Discussions {.unnumbered}

### Reflective Practice Discussions {.unnumbered}

Experiential learning provides a rich opportunity for learners to integrate course learning with engagement in facilitating learning to address training/development needs in an organization. As part of this process, students will engage in reflective practice.

As part of reflective practice, learners will keep regular field notes of their practicum experience, including specific observations, interview notes, descriptions of experiences, etc.

> "Field notes are the primary way of capturing the data that is collected from participant observations. Notes taken to capture this data include records of what is observed, including informal conversations with participants, records of activities and ceremonies, during which the researcher is unable to question participants about their activities, and journal notes that are kept on a daily basis" (Kawulich, 2005).

Experiential learning is strongest when it synthesizes practical experience with prior knowledge and academic literature. Writing can be a powerful learning experience. Through discussions, learners will engage in reflective practice, including reflection and critical analysis of their practicum experience, organizing and integrating new knowledge with prior knowledge through regular writing practice.

Learners will complete Reflective Practice Discussions using a reflective practice model they select.

### Reflective Practice Discussion 1: Experiential Learning {.unnumbered}

Write a discussion post. Describe the context in which you will conduct your experiential learning (practicum). (Consider whether you want or need to keep the site anonymous and, if so, be sure to avoid identifying details.) List the learning outcomes you developed for your practicum experience (from your Practicum Proposal). Specifically describe how you will assess your own learning. Discuss how your practicum experience will align with your personal identity, values, and beliefs as a teacher/facilitator.

Respond to the posts of two other learners, providing reflective feedback on their learning outcomes, practicum experience, and/or their integration of their identity, values, and beliefs with their practicum plans.

### Reflective Practice Discussion 2: Applying a Reflective Practice Model {.unnumbered}

Outline a plan for how you will apply the key elements of Gibb’s (1988) Reflective Cycle, in your classroom observations and teaching/facilitation experience.

Respond to the posts of two other learner’s, providing suggestions for how they might maximize their experience of the reflective cycle in their practicum.

### Reflective Practice Discussion 3 and 4: Classroom Observation {.unnumbered}

Observe another teacher/facilitator for a minimum of 10 hours.

Write two discussion posts (the first after you have completed approximately half of your observation hours, and the second after you have completed most of your hours).

Using the reflective practice model you selected, analyze the lesson plan design, learning activities, and assessment strategies you observe in your classroom observation. In the analysis stage, discuss which (if any) theories of adult education and principles of a community of learning were implemented during the learning experience.

At the end of your discussion, pose an open-ended question to other practicum learners. Respond to the posts of two other learners, expanding on their experience, use of reflective practice, and/or asking a question about their experience.

### Reflective Practice Discussions 5, 6,and 7: Designing Learning Experiences {.unnumbered}

#### Reflective Practice Discussion 5: LESSON PLAN 1: Authentic and Inclusive Learning Experiences {.unnumbered}

Post your draft Lesson Plan in a discussion post for feedback from your instructor and other learners. You may also share with your practicum supervisor, as appropriate.

[Lesson Plan Template](https://far.twu.ca/ldrs/667/assignments/assignment-1/chromeless:true/Lesson.Plan.Template.docx){target="_blank"}

*Provide feedback to two other learners on their learning outcomes, learning activity, and/or assessments tools. Also, provide helpful input on their inclusion of adult learning theory and/or community of learning principle.*

#### Reflective Practice Discussion 6: LESSON PLAN 2: Cultural Competency {.unnumbered}

Post your draft Lesson Plan in a discussion post for feedback from your instructor and other learners. You may also share with your practicum supervisor, as appropriate.

[Lesson Plan Template](https://far.twu.ca/ldrs/667/assignments/assignment-1/chromeless:true/Lesson.Plan.Template.docx){target="_blank"}

*Provide feedback to two other learners on their learning outcomes, learning activity, and/or assessments tools. Also, provide helpful input on their inclusion of adult learning theory and/or community of learning principle.*

#### Reflective Practice Discussion 7: LESSON PLAN 3: Critical and Creative Thinking {.unnumbered}

Post your draft Lesson Plan in a discussion post for feedback from your instructor and other learners. You may also share with your practicum supervisor, as appropriate.

[Lesson Plan Template](https://far.twu.ca/ldrs/667/assignments/assignment-1/chromeless:true/Lesson.Plan.Template.docx){target="_blank"}

*Provide feedback to two other learners on their learning outcomes, learning activity, and/or assessments tools. Also, provide helpful input on their inclusion of adult learning theory and/or community of learning principle.*

#### Reflective Practice Discussions 8, 9, and 10: Teaching/Facilitating {.unnumbered}

**Reflective Practice Discussion 8:** Write a discussion post in which you use Gibbs' (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 1.

**Reflective Practice Discussion 9:** Write a discussion post in which you use Gibbs' (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 2.

**Reflective Practice Discussion 10:** Write a discussion post in which you use Gibbs' (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 3.

### Grading Criteria: REFLECTIVE PRACTICE DISCUSSION RUBRIC {.unnumbered}

**RUBRIC: Reflective Practice Discussions**

|                                                               | Unsatisfactory 0%                                                                                                                                                                                             | Developing 50% (C)                                                                                                                                                                                                                                                                                              | Proficient 75% (B)                                                                                                                                                                                                                                                                                                                              | Exemplary 100% (A)                                                                                                                                                                                                                                                                                                                                                                                                                                 |  |  |
|----------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--|---|
| REFLECTIVE PRACTICE MODEL (50%)                                | Original discussion post does not include analysis of teaching/facilitation practice through a reflective practice model. Some steps of the model are missing or incomplete.                                  | Original discussion post includes description of teaching/facilitation practice through a reflective practice model. Only some steps in the model are included in the analysis.                                                                                                                                 | Original discussion post includes analysis of teaching/facilitation practice through a reflective practice model. All steps in the model are included in the analysis.                                                                                                                                                                          | Original discussion post includes insightful analysis of teaching/facilitation practice through a reflective practice model. All steps in the model are included in the analysis.                                                                                                                                                                                                                                                                  |  |   |
| Analysis, Evaluation, AND APPLICATION of SCHOLARLY SOURCES 20% | Discussion post does not include evaluation synthesis, and application of scholarly sources. Discussion post and responses do not include references to scholarly sources.                                    | Discussion post includes incomplete evaluation and/or synthesis and/or application of scholarly sources. Discussion post and responses only partially support academic arguments with scholarly sources.                                                                                                        | Original discussion post includes evaluation, synthesis, and application of scholarly sources. Discussion post includes references to scholarly, peer-reviewed texts or other resources to support academic arguments in both original and reply posts.                                                                                         | Discussion post includes evaluation, synthesis, and application of scholarly sources, demonstrating original thought. Discussion post includes references to scholarly, peer-reviewed resources, incorporating non-course scholarly resources to augment the academic argument.                                                                                                                                                                    |  |   |
| COMMUNITIY Of LEARNING 20%                                     | Discussion post does not include an open-ended prompt. Responses to other learners are incomplete or superficial. Discussion posts and responses to do not demonstrate the values of a community of learning. | Open-ended prompt in Discussion post does not prompt scholarly inquiry of other learners. Responses to other leaners are complete but do not expand on their scholarly thinking. Discussion posts and responses demonstrate only some values of a community of learning. Some content contradicts these values. | Original Discussion post includes an open-ended prompt to expand the scholarly inquiry of other learners. Responses to other learners expands on their scholarly thinking. Discussion posts and responses demonstrate values of a community of learning, including respect, inclusivity, creativity scholarly thinking, and academic integrity. | Discussion post includes an open-ended prompt to expand the scholarly inquiry of others and challenges others to consider different perspectives. Responses to other learners expands on their scholarly thinking and introduces them to new scholarly concepts or resources. Discussion posts and responses demonstrate values of a community of learning and demonstrate a value for other learners’ scholarly thinking and academic creativity. |  |   |
| APA/Writing 10%                                                | Writing is not well-organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.                                                                | Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.                                                                                                                             | Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.                                                                                                                   | Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.                                                                                                                                                                                                                                                                                                            |  |   |
| TOTAL                                                          | 0= 0% (F)                                                                                                                                                                                                     | 10 = 50% (C)                                                                                                                                                                                                                                                                                                    | 15 = 75 (B)                                                                                                                                                                                                                                                                                                                                     | 20 = 100% (A+)                                                                                                                                                                                                                                                                                                                                                                                                                                     |

## Practicum Proposals {.unnumbered}

In preparation for the practicum, write a 3-5 page Practicum Proposal, including the following sections:

1. **Practicum Site:** Include a description of the context in which you will conduct your practicum. Although you need to identify your site for this assignment, you should consider whether you want to keep the site anonymous for your discussions in the Practicum Course. If so, be sure to indicate in your proposal how you will avoid identifying details in course discussions.
2. **Practicum Mentor:** Include the signed Mentor Agreement
3. **Learning Outcomes:** Include three personal learning outcomes that will shape your experiential learning in this practicum. What do you want to learn during the practicum experience?
4. **Planned Schedule for 20 Hours of Experiential Learning, to include:**
   1. Observation of Teaching (Minimum of 10 hours)
   2. Designing and Facilitating Lessons/Classes (Minimum of 10 hours, Minimum of 3 Lessons)
   3. Facilitating Online or Face-to-Face Discussions
5. **Learning:** An analysis of how this practicum will contribute to the achievement of practicum learning outcomes
6. **Career Planning:** A discussion of how this practicum will build on your current academic, personal, and professional knowledge, and how it will contribute to your career goals.

### Rubric: Practicum Proposal {.unnumbered}

|                                                 | Unsatisfactory 0%                                                                                                                                                                                                                                                                                                                                                          | Developing 50% (C)                                                                                                                                                                                                                                                                                                                                                                                       | Proficient 75% (B)                                                                                                                                                                                                                                                                                                                      | Exemplary 100% (A)                                                                                                                                                                                                                                                                                                                                                                      |  |
|--------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--|
| Practicum site (10%)                             | Does not includes a description of the context in which the practicum will be conducted. If the site will be anonymous to other learner, does not include a plan for how identifying details will be avoided in course discussions. Does not include a signed mentor agreement.                                                                                            | Includes an incomplete description of the context in which the practicum will be conducted. If the site will be anonymous to other learner, includes an incomplete plan for how identifying details will be avoided in course discussions. Note: A mentor agreement is included but is incomplete.                                                                                                       | Includes a description of the context in which the practicum will be conducted. If the site will be anonymous to other learner, includes a plan for how identifying details will be avoided in course discussions. Note: A signed mentor agreement is required before the practicum can begin.                                          | Includes a description of the context in which the practicum will be conducted, including an analysis of the learning environment. If the site will be anonymous to other learner, includes a plan for how identifying details will be avoided in course discussions. Note: A signed mentor agreement is required before the practicum can begin.                                       |  |
| PRACTICUM Learning Outcome(s) (20%)              | Does not include three learning outcomes for the practicum clearly align with program learning outcomes. LOs are not at an appropriate level for graduate-level practicum. The LOs do not begin with “At the completion of this practicum, I will be able to…”, and/or do not include one learning verb (apply, analyze, etc.) and/or one noun (what students will learn). | The learning outcomes for the practicum do not clearly align with program learning outcomes. LOs are at close to being at appropriate level for graduate-level practicum. The LOs do not begin with “At the completion of this practicum, I will be able to…”, and/or includes more than/less than one learning verb (apply, analyze, etc.) and more than/less than one noun (what students will learn). | The learning outcomes for the practicum align with program learning outcomes. Learning outcomes are at an appropriate level for a graduate-level practicum. The LOs begin with “At the completion of this practicum, I will be able to…”, and include one learning verb (apply, analyze, etc.) and one noun (what students will learn). | The learning outcomes for the practicum clearly align with program learning outcomes. LOs are at an appropriate level for graduate-level practicum and will expand the expertise of the practicum student. The LOs begin with “At the completion of this practicum, I will be able to…”, and includes one learning verb (apply, analyze, etc.) and one noun (what students will learn). |  |
| SCHEDULE FOR EXPERIENTIAL LEARNING (10%)         | Does not includes a plan to achieve the requirements of a minimum of 10 hours of classroom observation, and 10 hours of curriculum design and facilitation.                                                                                                                                                                                                                | Includes a vague plan to achieve the requirements, but does not specifically include a plan for a minimum of 10 hours of classroom observation, and/or 10 hours of curriculum design and facilitation.                                                                                                                                                                                                   | Includes a specific plan to achieve the requirements of a minimum of 10 hours of classroom observation, and 10 hours of curriculum design and facilitation.                                                                                                                                                                             | Includes a specific plan to achieve the requirements of a minimum of 10 hours of classroom observation, and 10 hours of curriculum design and facilitation, including specific dates/times.                                                                                                                                                                                             |  |
| ACHIEVEMENT OF PRACTICUM LEARNING OUTCOMES (20%) | Does not includes an analysis of how the practicum will contribute to achievement of practicum learning outcomes.                                                                                                                                                                                                                                                          | Includes a vague description of how this practicum will contribute to achievement of practicum learning outcomes, or does not address all learning outcomes.                                                                                                                                                                                                                                             | Includes an analysis of how this practicum will contribute to achievement of practicum learning outcomes.                                                                                                                                                                                                                               | Includes an insightful analysis of how this practicum will contribute to achievement of practicum learning outcomes, integrating scholarly sources to support this analysis.                                                                                                                                                                                                            |  |
| CAREER PREPARATION (10%)                         | Does not includes a discussion of how this practicum will build on student’s current academic, personal, and professional knowledge. Does not include an explanation of how it will contribute to career goals.                                                                                                                                                            | Includes a partial discussion of how this practicum will build on student’s current academic, personal, and professional knowledge OR includes a partial explanation of how it will contribute to career goals.                                                                                                                                                                                          | Includes a discussion of how this practicum will build on student’s current academic, personal, and professional knowledge. Includes an explanation of how it will contribute to career goals.                                                                                                                                          | Includes an analysis of how this practicum will build on student’s current academic, personal, and professional knowledge. Includes an explanation of how it will contribute to career goals. Includes references to scholarly, peer-reviewed resources to support this analysis.                                                                                                       |  |
| APA/Writing (10%)                                | The practicum proposal does not follows the proposal guidelines and/or writing is not well-organized and includes several errors in grammar or composition and/or some resources are not appropriately cited using APA format.                                                                                                                                             | The practicum proposal follows some of the proposal guidelines. Writing is somewhat organized and includes a few errors in grammar or composition. All resources are cited, but there are some errors in APA format.                                                                                                                                                                                     | The practicum proposal follows the template. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited using APA format.                                                                                                                                              | The practicum proposal follows the template. Writing is well-organized and includes no errors in grammar or composition. All resources are appropriately cited using APA format.                                                                                                                                                                                                        |  |
| POSSIBLE POINTS                                  | 0                                                                                                                                                                                                                                                                                                                                                                          | 50                                                                                                                                                                                                                                                                                                                                                                                                       | 75                                                                                                                                                                                                                                                                                                                                      | 100                                                                                                                                                                                                                                                                                                                                                                                     |

## Lesson Plan Design and Implementation {.unnumbered}

Learners will complete a minimum of 10 hours of lesson plan design and implementation, including the design of three lesson plan and the facilitation of three lesson plans. (Ideally, learners will facilitation the lesson plans they design, although that may not always be possible.) Learners will use the Lesson Plan Template for each lesson plan, which includes: Lesson Topic, Learning Outcomes, Learning Activities, and Learning Assessment. Each unit will include a specific focus (LP1: Authentic/Inclusive Learning, LP2: Culturally-Inclusive Communication, LP3: Creative/Critical Thinking) and will include 1) one of the six principles of the Community of Learning (Boyer, 1990), and 2) a specific adult learning theory.

### Lesson Plan: Template {.unnumbered}

Download and use the [Lesson Plan Template](https://far.twu.ca/ldrs/667/assignments/assignment-3/LDRS_667_Lesson_Plan_Template.docx){target="_blank"}.

### RUBRIC: Lesson Plan {.unnumbered}

See the following [Lesson Plan Rubric](https://far.twu.ca/ldrs/667/assignments/assignment-3/LDRS_667_Lesson_Plan_Rubric.pdf){target="_blank"}.

#### ASSESSMENT OF LEARNING: LESSON PLAN DESIGN AND IMPLEMENTATION {.unnumbered}

**RUBRIC: Lesson Plan**

|                                                                                                              | UNSATISFACTORY                                                                                                                                                                                                                                                      | DEVELOPING                                                                                                                                                                                                                                                                                   | PROFICIENT                                                                                                                                                                                                                     | EXEMPLARY                                                                                                                                                                                                                                                                                                                                          |
|---------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                               | 0%                                                                                                                                                                                                                                                                  | 50% (C)                                                                                                                                                                                                                                                                                      | 75% (B)                                                                                                                                                                                                                        | 100% (A)                                                                                                                                                                                                                                                                                                                                           |
| LEARNING OUTCOME(S)                                                                                           | There are no learning outcome(s) for the lesson, or they do not align with course learning outcomes. learning outcomes are not at an appropriate level for the unit and course.                                                                                     | The learning outcome(s) for the lesson do not fully align with the course learning outcomes. learning outcomes are close to being at an appropriate level for the unit and course.                                                                                                           | The learning outcome(s) for the lesson align with the course learning outcomes. learning outcomes are at an appropriate level for the unit and course.                                                                         | The learning outcome(s) for the lesson clearly align with the course learning outcomes. learning outcomes are at an appropriate level for the unit and course. The learning outcome begins with “Students will be able to…”, and includes one learning verb (apply, analyze, etc.) and one noun (what students will learn).                        |
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
| -20%                                                                                                          | The learning outcome does not begin with “Students will be able to…”, and includes more than/less than one learning verb (apply, analyze, etc.) and more than/less than one noun (what students will learn).                                                        | The learning outcome begins with “Students will be able to…”, or includes one learning verb (apply, analyze, etc.) or includes one noun (what students will learn).                                                                                                                          | The learning outcome begins with “Students will be able to…”, and includes one learning verb (apply, analyze, etc.) and one noun (what students will learn).                                                                   |                                                                                                                                                                                                                                                                                                                                                    |
| LEARNING ACTIVITY (20%)                                                                                       | The learning activity(s) does not prepare students to achieve the lesson Learning outcome(s). The learning activity does not include principles or strategies from scholarly readings. The learning activity does not prepare students for the learning assessment. | The learning activity(s) may or may not prepare students to achieve the lesson Learning outcome(s). The learning activity vaguely includes principles or strategies which may or may not be scholarly readings. The learning activity vaguely prepares students for the learning assessment. | The learning activity(s) is an effective learning experience to achieve the lesson Learning outcome(s).                                                                                                                        | The learning activity(s) is a highly effective learning experience to achieve the lesson Learning outcome(s). The learning activity incorporates specific principles or strategies from scholarly readings that have been demonstrated to result in student learning. The learning activity clearly prepares students for the learning assessment. |
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              | The learning activity incorporates specific principles or strategies from scholarly readings.                                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              | The learning activity clearly prepares students for the learning assessment.                                                                                                                                                   |                                                                                                                                                                                                                                                                                                                                                    |
| LEARNING                                                                                                      | The learning assessment does not effectively measure student achievement of the Learning outcome(s).                                                                                                                                                                | The learning assessment will measure some but not all student achievement of the Learning outcome(s).                                                                                                                                                                                        | The learning assessment effectively measures student achievement of the Learning outcome(s).                                                                                                                                   | The learning assessment effectively measures student achievement of the Learning outcome(s). Includes references to scholarly literature to support the choice of assessment measure.                                                                                                                                                              |
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
| ASSESSMENT (20%)                                                                                              |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
| LESSON FOCUS (20%)                                                                                            | The lesson plan does not integrate the key competency for the lesson (LP1: Authentic/Inclusive Learning, LP2: Culturally-Inclusive Communication, LP3: Creative/Critical Thinking) as part of the student learning experience.                                      | The lesson plan incompletely integrates the key competency for the lesson (LP1: Authentic/Inclusive Learning, LP2: Culturally-Inclusive Communication, LP3: Creative/Critical Thinking) as part of the student learning experience.                                                          | The lesson plan clearly integrates the key competency for the lesson (LP1: Authentic/Inclusive Learning, LP2: Culturally-Inclusive Communication, LP3: Creative/Critical Thinking) as part of the student learning experience. | The lesson plan clearly integrates the key competency for the lesson (LP1: Authentic/Inclusive Learning, LP2: Culturally-Inclusive Communication, LP3: Creative/Critical Thinking) as part of the student learning experience, including references to the scholarly literature to support lesson plan design.                                     |
|                                                                                                               |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
| (LP1: AUTHENTIC/INCLUSIVE LEARNING, LP2: CULTURALLY-INCLUSIVE COMMUNICATION, LP3: CREATIVE/CRITICAL THINKING) |                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                    |
| COMMUNITY OF LEARNING PRINCIPLE (5%)                                                                          | The lesson plan does not include an explanation of how students will engage with one of the Community Learning Principles (Boyer, 1990).                                                                                                                            | The lesson plan refers to but does not explain how students will engage with one of the Community Learning Principles (Boyer, 1990).                                                                                                                                                         | The lesson plan includes a clear explanation of how students will engage with one of the Community Learning Principles (Boyer, 1990).                                                                                          | The lesson plan includes a clear explanation of how students will engage with one of the Community Learning Principles (Boyer, 1990), including references to other scholarly sources, in addition to Boyer.                                                                                                                                       |
| INTEGRATION OF ADULT LEARNING THEORY (5%)                                                                     | The lesson plan does not explain how adult learning theory is incorporated into the learning activity.                                                                                                                                                              | The lesson plan refers to but does not explain how adult learning theory is incorporated into the learning activity.                                                                                                                                                                         | The lesson plan includes a clear explanation of how adult learning theory is incorporated into the learning activity.                                                                                                          | The lesson plan includes a clear explanation of how adult learning theory is incorporated into the learning activity, including references to scholarly literature.                                                                                                                                                                                |
| APA/WRITING (10%)                                                                                             | The lesson plan does not follow the template and/or Writing is not well-organized and includes several errors in grammar or composition and/or some resources are not appropriately cited using APA format.                                                         | The lesson plan generally follows the template. Writing is somewhat organized and includes a few errors in grammar or composition. All resources are cited, but there are some errors in APA format.                                                                                         | The lesson plan follows the template. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited using APA format.                                            | The lesson plan follows the template. Writing is well-organized and includes no errors in grammar or composition. All resources are appropriately cited using APA format.                                                                                                                                                                          |
| POSSIBLE POINTS                                                                                               | 0                                                                                                                                                                                                                                                                   | 50                                                                                                                                                                                                                                                                                           | 75                                                                                                                                                                                                                             | 75                                                                                                                                                                                                                                                                                                                                                 |

## Reflective Practice Practicum Portfolio {.unnumbered}

Upon completion of the 20 practicum hours, learners will prepare a Reflective Practice Portfolio (15-20 pages) that synthesizes the practicum experience with current literature and prior knowledge. This portfolio will include the Classroom Observation Logs, Facilitation Log, and Verification of Hours, as well as Lesson Plans designed during the practicum. It will also include new writing, which will synthesize the reflective practice discussions, and include summative evaluation and analysis of learning in the practicum experience.

This paper will be written using APA format and will be based on Gibb’s (1988) Reflective Cycle. The paper will include the following sections:

1. Title Page
2. Table of Contents
3. Introduction and Practicum Learning Outcomes (1-2 pages)
4. Description:
   - Classroom Observation Log, Facilitation Log, and Verification of Hours (1 page)
   - Lesson Plan 1 (2-3 pages)
   - Lesson Plan 2 (2-3 pages)
   - Lesson Plan 3 (2-3 pages)
5. Feelings (1-2 pages)
6. Evaluation (1-2 page)
7. Analysis (1-2 pages)
8. Conclusion and Action Plan (1-2 pages)
9. Reference List

### RUBRIC: Reflective Practice Practicum Portfolio {.unnumbered}

|                                                          | UNSATISFACTORY                                                                                                                                                                                                                                                                                                           | DEVELOPING                                                                                                                                                                                                                                                                                                                                                                                                   | PROFICIENT                                                                                                                                                                                                                                                                                                                                                 | EXEMPLARY                                                                                                                                                                                                                                                                                                                                                   |
|-----------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | 0%                                                                                                                                                                                                                                                                                                                       | 50% (C)                                                                                                                                                                                                                                                                                                                                                                                                      | 75% (B)                                                                                                                                                                                                                                                                                                                                                    | 100% (A)                                                                                                                                                                                                                                                                                                                                                    |
| INTRODUCTION (10%)                                        | Does not includes an introduction to the practicum portfolio. Does not list the practicum learning outcomes.                                                                                                                                                                                                             | Includes an introduction to the practicum portfolio or lists some or none of the practicum learning outcomes.                                                                                                                                                                                                                                                                                                | Includes an introduction to the practicum portfolio. Lists each of the practicum learning outcomes.                                                                                                                                                                                                                                                        | Includes an introduction to the practicum portfolio, Gibb’s (1988) Reflective Practice Model. Lists each of the practicum learning outcomes, and includes an explanation of how specific elements of the portfolio demonstrate achievement of learning outcomes.                                                                                            |
| DESCRIPTION (15%)                                         | Does not include a description of the practicum experience.                                                                                                                                                                                                                                                              | Does not include a description of the practicum experience.                                                                                                                                                                                                                                                                                                                                                  | Includes a description of the practicum experience.                                                                                                                                                                                                                                                                                                        | Includes an insightful description of the practicum experience, integrating scholarly sources to support description.                                                                                                                                                                                                                                       |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not include Classroom Observation Log, Facilitation Log, and/or Verification of Hours. (Note: These are all required to pass the Practicum).                                                                                                                                                                        | Includes some, but not all of the following: Classroom Observation Log, Facilitation Log, and/or Verification of Hours. (Note: These are all required to pass the Practicum).                                                                                                                                                                                                                                | Includes all of the following: Classroom Observation Log, Facilitation Log, and Verification of Hours. (Note: These are all required to pass the Practicum).                                                                                                                                                                                               | Includes all of the following: Classroom Observation Log, Facilitation Log, and Verification of Hours. (Note: These are all required to pass the Practicum).                                                                                                                                                                                                |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not includes three Lesson Plans.                                                                                                                                                                                                                                                                                    | Does not includes three Lesson Plans.                                                                                                                                                                                                                                                                                                                                                                        | Includes three Lesson Plans.                                                                                                                                                                                                                                                                                                                               | Includes three Lesson Plans                                                                                                                                                                                                                                                                                                                                 |
| FEELINGS (15%)                                            | Does not include an analysis of feelings related to the practicum experience. Does not include a discussion of how students may have felt during and about the learning activities. Does not include a summative analysis of feelings about the practicum as a whole.                                                    | Includes an analysis of feelings related to the practicum experience, including some (but not all) of the following: feelings before, during, and after the classroom observation, lesson plan design, and facilitation and/or includes a discussion of how students may have felt during and about the learning activities and/or includes a summative analysis of feelings about the practicum as a whole. | Includes an analysis of feelings related to the practicum experience, including feelings before, during, and after the classroom observation, lesson plan design, and facilitation. Includes a discussion of how students may have felt during and about the learning activities Includes a summative analysis of feelings about the practicum as a whole. | Includes an analysis of feelings related to the practicum experience, including feelings before, during, and after the classroom observation, lesson plan design, and facilitation. Includes a discussion of how students may have felt during and about the learning activities Includes a summative analysis of feelings about the practicum as a whole.  |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            | The analysis includes references to the literature related to Gibb’s Reflective Practice and/or other scholarly sources.                                                                                                                                                                                                                                    |
| EVALUATION (15%)                                          | Does not include an evaluation of all elements of the practicum experience: classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                 | Includes an evaluation of one or more parts of the practicum experience: classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                                                        | Includes an evaluation of the practicum experience, including classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                 | Includes an evaluation of the practicum experience, including classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                  |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | The evaluation does not include a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.                                                                                                                                                      | The evaluation includes a description of some of the following: what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.                                                                                                                                                                                                                           | The evaluation includes a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.                                                                                                                                                                                                | The evaluation includes a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.                                                                                                                                                                                                 |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            | Incorporates references to scholarly literature to support evaluation.                                                                                                                                                                                                                                                                                      |
| ANALYSIS (15%)                                            | Does not include an analysis of all elements of the practicum experience: classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                   | Includes an analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                                                                     | Includes an analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                   | Includes an insightful analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                         |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not include an analysis of all the following: why things went well, why things didn’t go well, and the meaning of this experience. Does not incorporate other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis.                                                | Includes an incomplete analysis of some of the following: why things went well, why things didn’t go well, and the meaning of this experience. Minimally incorporates other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis.                                                                                                                           | Includes an analysis of why things went well, why things didn’t go well, and the meaning of this experience. Incorporates other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis.                                                                                                                     | Includes an insightful analysis of why things went well, why things didn’t go well, and the meaning of this experience.                                                                                                                                                                                                                                     |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not include a discussion of how each practicum learning outcome was achieved.                                                                                                                                                                                                                                       | Includes a discussion of how some of the practicum learning outcome were achieved.                                                                                                                                                                                                                                                                                                                           | Includes a discussion of how each practicum learning outcome was achieved.                                                                                                                                                                                                                                                                                 | Synthesizes the analysis with other resources (including scholarly sources, practicum feedback, and discussion feedback).                                                                                                                                                                                                                                   |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              | Synthesize personal identity, values, and beliefs into the facilitation and teaching process                                                                                                                                                                                                                                                               | Includes a discussion of how each practicum learning outcome was achieved.                                                                                                                                                                                                                                                                                  |
| DEVELOPING A COHESIVE AND LOGICAL ACADEMIC ARGUMENT (10%) | Does not make a focused, cohesive, or logical academic argument. Paper is confusing, and is missing some of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are missing. | Makes an academic argument that is only partially focused, cohesive and logical. Paper is generally organized but is missing some of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are unclear.                                                            | Makes a focused, cohesive, logical academic argument. Paper is effectively organized and includes all of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are clear.                                        | Makes a focused, cohesive, logical and compelling academic argument. Paper is effectively organized and includes all of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are clear, and build on each other. |
| SCHOLARLY INTEGRATION (10%)                               | Does not integrate references to support claims and assertions made in the paper.                                                                                                                                                                                                                                        | Integrates references to support some of the claims and assertions made in the paper.                                                                                                                                                                                                                                                                                                                        | Integrates references to support claims and assertions made in the paper.                                                                                                                                                                                                                                                                                  | Integrates references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.                                                                                                                                                                                      |
| APA/WRITING (10%)                                         | Paper does not model language and conventions used in scholarly literature. Writing is not well-organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.                                                                                               | Paper partially models language and conventions used in scholarly literature. Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.                                                                                                                                            | Paper consistently models language and conventions used in scholarly literature. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.                                             | Paper is an exemplar of language and conventions used in scholarly literature. Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.                                                                                                                                      |
| TOTAL                                                     | 0% (F)                                                                                                                                                                                                                                                                                                                   | 50% (C)                                                                                                                                                                                                                                                                                                                                                                                                      | 75% (B)                                                                                                                                                                                                                                                                                                                                                    | 100% (A+)                                                                                                                                                                                                                                                                                                                                                   |
