# Teaching/facilitating

## Overview {.unnumbered}

In Unit 4, we focus on designing learning experiences that create the opportunities for students to achieve course learning outcomes. Unit 4 will be completed over several weeks of your practicum, and will be completed at the same time as Unit 2 Classroom Observation and Unit 3 Designing Learning Experiences. In this unit, you will facilitate a minimum of three lesson plans in your practicum setting. Ideally, you will facilitate the lesson plans you designed in Unit 3. However, if that is not practical, you can facilitate lessons that have already been designed. Your facilitation can be conducted in a face-to-face or online setting, and can be synchronous or asynchronous. For example, you might facilitate:

- a face-to-face class discussion
- an online discussion
- a synchronous video class
- a face-to-face learning activity

### Topics {.unnumbered}

In this unit, we will focus on:

1. Teaching/Facilitation Strategies

### Learning Outcomes {.unnumbered}

In this unit, you will teach/facilitate a minimum of three lessons. By the end of this unit, you should be able to:

- Facilitate lessons using effective facilitation skills.
- Engage in reflective practice.

### Activity Checklist {.unnumbered}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

::: {.note}

**Learning Activities **

- Teach/facilitate a minimum of three lessons, in an online or face-to-face environment. (Note: You will complete a minimum of 10 hours of curriculum design and facilitation, combined). Ideally, you will facilitate a lesson plan you designed, however, that may not always be practical.
- Engage in reflective practice throughout the teaching/facilitation process.
- Complete the Facilitation Log (The log be submitted as part of your Reflective Practice Practicum Portfolio).

:::

::: {.note}

**Assessment**

- Reflective Practice Discussion 8: Write a discussion post in which you use Gibb’s (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 1
- Reflective Practice Discussion 9: Write a discussion post in which you use Gibb’s (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 2
- Reflective Practice Discussion 10: Write a discussion post in which you use Gibb’s (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 3.

:::

## Teaching/facilitation Strategies

In this unit, you will facilitate a minimum of three lessons in an online or face-to-face environment, each with a specific focus. Ideally, you will facilitate lessons you have designed, however, if that is not practical, you will facilitate a lesson designed by someone else.

Facilitating learning – whether online or face-to-face – requires an effective facilitator, engaged students, and well-developed plans for learning. Effective facilitation requires much more than delivery of content; telling someone something simply isn’t the same as teaching them something.

In LDRS 627, you reviewed strategies for facilitating social-emotional learning and employing sensory-engaged pedagogies, incorporating all the senses (sight, sound, smell, taste and touch) in the teaching learning process.

Examples of sensory-engaged teaching methods highlighted in LDRS 627:

- auditory input such as recorded lectures; incorporation of music
- visuals - analysis of videos and film; incorporation of art
- problem-solving through case studies
- storytelling
- place-based learning including learning in nature and other environments
- kinesthetic or movement learning activities e.g. role play
- activities that incorporate the olfactory (sense of smell) e.g. bringing in spices from a region to evoke the culture of food
- activities that incorporate the sense of touch - textured materials, manipulatives
- discussion forums
- use of interactive technology

As you prepare to facilitate your lessons, you might find it helpful to review Silberman and Biech (2015). According to Silberman and Biech (2015), "Preparation is one of the most important ingredients for success" (p. 207). You can gain credibility as a trainer by setting group norms, eliminating time wasters, being able to getting the group’s attention, winning over wary participants and managing difficult behaviors (p. 208). More details and specific strategies are recommended in chapters 11-15.

As discussed in LDRS 627, Silberman and Biech (2015) also provide many practical strategies chapter 3 has many practical strategies for team building, just-in-time assessment and active learning. You may want to review Chapter 3 to explore strategies for: open discussion, response cards, polling, subgroup discussions, partners, go-arounds, games, calling on the next speaker, panels and fishbowls.

In Chapter 13, Wang (2017) discusses the effectiveness of opening exercises, considers learning resistance and practical strategies. According to Wang (2017), eye contact and relaxed body language, engaging students, being professional and organized, and creating a hospitable learning environment all serve to create the conditions for student learning and engagement. As you’ll recall from LDRS 627, simply having a plan to host a discussion about a given topic is not sufficient; you need to carefully plan how you will engage learners in the discussion, draw out those who may not readily participate, create an environment where disagreement is valued and respectful, and ensure that the information shared is accurate. You will also be striving to create an environment of inclusivity, where diverse viewpoints are valued and all students belong. For discussions, as with all other learning activities, preparation is required.

In preparation for your facilitation experience, you may find it helpful to review the work of Wang (2017), Silberman and Biech (2015), Palmer (2017), Brown (2018) and others. You may also want to review liberating structures, and other facilitation resources you’ve compiled.

**As you review these materials, consider:**

- What kind of first impression do I want to make? How can I do this?
- What teaching/facilitation strategies can I use to facilitate active learning?
- How can I create an environment of inclusivity in the class?
- What back-up plans do I need, in case the initial activity takes less time than I had planned?

As you facilitate each lesson, you will complete a Reflective Practice Discussion Post, using Gibb’s (1988) reflective practice cycle to reflect on this experience. As you engage in both facilitation and reflective practice, be sure to integrate the literature and other materials from previous courses in your practice of teaching/facilitating.

### Activity: Teaching/facilitating

::: {.learning-activity}

Teach/facilitate a minimum of three lessons, in an online or face-to-face environment. (Note: You will complete a minimum of 10 hours of curriculum design and facilitation, combined). Ideally, you will facilitate a lesson plan you designed, however, that may not always be practical.

:::

### Activity: Reflective Practice

::: {.learning-activity}

Engage in Reflective Practice throughout the Facilitation Process.

:::

### Activity: Facilitation Log

::: {.learning-activity}

Complete the Facilitation Log *(The log be submitted as part of your Reflective Practice Practicum Portfolio).*

:::

## Summary {.unnumbered}

In this unit, you have facilitated a minimum of three lessons in an online or face-to-face learning environment. Throughout this process, you have engaged in reflective practice through the use of Gibb’s (1988) reflective cycle.

## Assessment {.unnumbered}


**Reflective Practice Discussions 8, 9, and 10: Teaching/Facilitating**

- **Reflective Practice Discussion 8:** Write a discussion post in which you use Gibbs' (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 1.
- **Reflective Practice Discussion 9:** Write a discussion post in which you use Gibbs' (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 2.
- **Reflective Practice Discussion 10:** Write a discussion post in which you use Gibbs' (1988) reflective practice cycle to analyze your teaching/facilitation of Lesson 3.

## Checking Your Learning {.unnumbered}

::: {.check}

As you engage in Classroom Observation in this unit, continually remind yourself that through this experience, you should be able to:

- Facilitate lessons using effective facilitation skills.
- Engage in reflective practice.

:::

## References {.unnumbered}

- Silberman, M. L., & Biech, E. (2015). *Active training: A handbook of techniques, designs, case examples, and tips (4th ed.).* Hoboken, New Jersey: John Wiley & Sons
- Wang, C. X. (2017). *Theory and practice of adult and higher education*. Information Age Publishing Inc.
