# Teaching and Facilitation

## Overview {.unnumbered}

In Unit 4, we focused on designing learning experiences that create opportunities for students to achieve course learning outcomes. This unit will be completed over several weeks of your practicum, and will be completed at the same time as Unit 3 Classroom Observation and Unit 4 Designing Learning Experiences. In this unit, you will facilitate a minimum of three lesson plans in your practicum setting. Ideally, you will facilitate the lesson plans you designed in Unit 4. However, if that is not practical, you can facilitate lessons that have already been designed (by you or your practicum mentor). Your facilitation can be conducted in a face-to-face or online setting, and can be synchronous or asynchronous. For example, you might facilitate:

- a face-to-face class discussion
- an online discussion
- a synchronous video class
- a face-to-face learning activity

### Topics {.unnumbered}

In this unit, we will focus on:

1. Teaching/Facilitation Strategies

### Learning Outcomes {.unnumbered}

In this unit, you will teach/facilitate a minimum of three lessons. By the end of this unit, you should be able to:

- Facilitate lessons using effective facilitation skills.
- Engage in reflective practice.

### Learning Activities {.unnumbered}

Here is a checklist of learning activities you will benefit from as you complete this unit. You may find it useful for planning your work.

- Teach or facilitate a minimum of three lessons, in an online or face-to-face environment. (Note: You will complete a minimum of 10 hours of curriculum design and facilitation, combined. Ideally, you will facilitate a lesson plan you designed, however, that may not always be practical.)
- Engage in reflective practice throughout the teaching/facilitation process.
- Complete the Facilitation Log (The log will be submitted as part of your Reflective Practice Practicum Portfolio).

### Assessment {.unnumbered}

The assessment for this unit includes your engagement in reflective practice discussions, which are **Discussions 8-10**.

See the Assessment section in Moodle for more details.

## Teaching/Facilitation Strategies

In this unit, you will facilitate a minimum of three lessons in an online or face-to-face environment, each with a specific focus. Ideally, you will facilitate lessons you have designed, however, if that is not practical, you will facilitate a lesson designed by someone else.

Facilitating learning – whether online or face-to-face – requires an effective facilitator, engaged students, and well-developed plans for learning. Effective facilitation requires much more than delivery of content; telling someone something simply isn’t the same as teaching them something.

In LDRS 627, you reviewed strategies for facilitating social-emotional learning and employing sensory-engaged pedagogies, incorporating all the senses (sight, sound, smell, taste and touch) in the teaching learning process.

Examples of sensory-engaged teaching methods highlighted in LDRS 627:

- auditory input such as recorded lectures; incorporation of music
- visuals - analysis of videos and film; incorporation of art
- problem-solving through case studies
- storytelling
- place-based learning including learning in nature and other environments
- kinesthetic or movement learning activities e.g. role play
- activities that incorporate the olfactory (sense of smell) e.g. bringing in spices from a region to evoke the culture of food
- activities that incorporate the sense of touch - textured materials, manipulatives
- discussion forums
- use of interactive technology

As you prepare to facilitate your lessons, you might find it helpful to review Silberman and Biech (2015). According to Silberman and Biech (2015), "Preparation is one of the most important ingredients for success" (p. 207). As a facilitator, engaging participants in the learning activity begins by demonstrating your credibility to facilitate the session. You can do this by focusing on the group’s attention, minimizing time wasters, setting expectations for how you want the group to work together, and effectively guiding participants who are unengaged or disruptive (Silberman & Biech, 2015). More details and specific strategies are recommended in chapters 11-15.

We often teach the way we have been taught – even if it’s not effective. As a facilitator, exploring new strategies will allow you to expand your expertise beyond what you have observed as a student. Through this practicum, your goal is not perfection, but progress, as you develop your facilitation skills. You should therefore commit to experimenting with some new strategies – even if they feel uncomfortable at first. Finding what works for you, what aligns with your personality and approach, can be empowering, as you seek to create the kind of learning experiences that bring life and meaning to the learning experience. As you consider what strategies you want to experiment with, be sure to review Silberman and Biech (2015), who provide many practical strategies in Chapter 3 for team building, just-in-time assessment and active learning. You may want to review Chapter 3 to explore strategies for: open discussion, response cards, polling, subgroup discussions, partners, go-arounds, games, calling on the next speaker, panels and fishbowls.

In Chapter 13, Wang (2017) discusses the effectiveness of opening exercises, considers learning resistance and practical strategies. According to Wang (2017), eye contact and relaxed body language, engaging students, being professional and organized, and creating a hospitable learning environment all serve to create the conditions for student learning and engagement. As you’ll recall from LDRS 627, simply having a plan to host a discussion about a given topic is not sufficient; you need to carefully plan how you will engage learners in the discussion, draw out those who may not readily participate, create an environment where disagreement is valued and respectful, and ensure that the information shared is accurate. You will also strive to create an environment of inclusivity, where diverse viewpoints are valued and all students belong. For discussions, as with all other learning activities, preparation is required.

You may also want to explore the [Session Lab library](https://www.sessionlab.com/library){target="_blank"}, which offers templates and methods for facilitating engaging conversations and classes. The Session Lab is a space where individual facilitators can share their strategies with each other, as facilitators are often quite generous in sharing their techniques for engaging learning and collaboration.

Books like Lang’s (2021) Small Teaching: Everyday Lessons from the Science of Teaching and Darby and Lang’s (2019) Small Teaching Online: Applying Learning Science in Online Classes, also provide an overview of strategies proven by research to deepen student learning.

In preparation for your facilitation experience, you may find it helpful to review the work of Wang (2017), Silberman and Biech (2015), Palmer (2017), Brown (2018) and others. You may also want to review liberating structures, and other facilitation resources you’ve compiled.

**As you review these materials, consider:**

- What kind of first impression do I want to make? How can authentically show students they are welcome?
- What teaching/facilitation strategies can I use to facilitate active learning?
- How can I create an environment of inclusivity in the class?
- What back-up plans do I need, in case the initial activity takes less time than I had planned?

As you facilitate each lesson, you will complete a Reflective Practice Discussion Post, using Gibb’s (1988) reflective practice cycle to reflect on this experience. As you engage in both facilitation and reflective practice, be sure to integrate the literature and other materials from previous courses in your practice of teaching/facilitating.

### Activity: Classroom Observation & Facilitation Log

As a requirement for this course, you must complete a minimum of 10 hours of lesson plan design and facilitation combined.

During your practicum, you will teach or facilitate a minimum of three lessons in either an online or face-to-face setting. You are required to document these sessions using the Classroom Observation & Facilitation Log.

- [[Template] Classroom Observation & Facilitation Log](https://mytwu.sharepoint.com/:w:/r/sites/LearningDesign/_layouts/15/Doc.aspx?sourcedoc=%7B85FCC2BF-9A2B-4B8C-8645-969DF3BD1E6E%7D&file=LDRS%20667_Classroom%20Observation%20Log.docx&action=default&mobileredirect=true)

Note: You are required to submit the completed Classroom Observation & Facilitation Log, along with verification of hours, as part of your final assignment: Reflective Practice Practicum Portfolio.

## Summary {.unnumbered}

In this unit, you have facilitated a minimum of three lessons in an online or face-to-face learning environment. Throughout this process, you have engaged in reflective practice through the use of Gibb’s (1988) reflective cycle.

### Checking Your Learning {.unnumbered}

- Facilitate lessons using effective facilitation skills.
- Engage in reflective practice.

## References {.unnumbered}

- Silberman, M. L., & Biech, E. (2015). *Active training: A handbook of techniques, designs, case examples, and tips (4th ed.).* John Wiley & Sons
- Wang, C. X. (2017). *Theory and practice of adult and higher education*. Information Age Publishing Inc.
- Lang, J.M. (2021). *Small teaching: Everyday lessons from the science of learning* (2nd ed.) Jossey-Bass.
- Darby, F. & Lang, J.M. (2019*). Small teaching online: Applying learning science in online classrooms.* Jossey-Bass.

<!-- ## Discussion 8: Reflective Practice – Facilitation 1

### Instructions {.unnumbered}

Review Unit 2 for an overview of Gibb’s (1988) reflective practice cycle. Write a discussion post in which you use Gibbs’ (1988) cycle to analyze your first teaching/facilitation.

### Rubric {.unnumbered}

<table> <colgroup> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> </colgroup> <thead> <tr class="header"> <th><strong>Criteria</strong></th> <th><strong>Needs Improvement (0%)</strong></th> <th><strong>Developing</strong> <strong>(70%)</strong></th> <th><strong>Proficient</strong> <strong>(80%)</strong></th> <th><strong>Exemplary (100%)</strong></th> </tr> </thead> <tbody> <tr class="odd"> <td><strong>APA/Writing</strong></td> <td>Writing is not well organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.</td> <td>Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.</td> <td>Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.</td> <td>Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.</td> </tr> <tr class="even"> <td><strong>Developing a Cohesive and Logical Academic argument</strong></td> <td>Does not make a focused, cohesive, or logical academic argument. Posts and responses are confusing, and is missing an introduction, body, or conclusion. Transitions between sections and ideas are missing.</td> <td>Makes an academic argument that is only partially focused, cohesive and logical. Posts and responses are generally organized, but are missing an introduction, body, or conclusion. Transitions between sections and ideas are unclear.</td> <td>Makes a focused, cohesive, logical academic argument. Posts and responses are effectively organized and include an introduction, body, and conclusion. Transitions between sections and ideas are clear.</td> <td>Makes a focused, cohesive, logical and compelling academic argument. Posts and responses are effectively organized and include an introduction, body, and conclusion. Transitions between sections and ideas are clear, and build on each other.</td> </tr> <tr class="odd"> <td><strong>Interview Synopsis and Analysis</strong></td> <td>Does not include a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Does not include an analysis.</td> <td>Lists but does not discuss key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a partial analysis.</td> <td>Includes a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a thoughtful analysis.</td> <td>Includes a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a thoughtful analysis, integrating scholarly literature to support analysis and furthering scholarly thinking related to inclusive learning environments.</td> </tr> <tr class="even"> <td><strong>Scholarly Integration</strong></td> <td>Does not integrate references to support claims and assertions made in the paper.</td> <td>Integrates references to support some of the claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.</td> </tr> <tr class="odd"> <td></td> <td><strong>Needs Improvement (0%)</strong></td> <td><strong>Developing</strong> <strong>(70%)</strong></td> <td><strong>Proficient</strong> <strong>(80%)</strong></td> <td><strong>Exemplary (100%)</strong></td> </tr> </tbody> </table>

## Discussion 9: Reflective Practice – Facilitation 2

### Instructions {.unnumbered}

Review Unit 2 for an overview of Gibb’s (1988) reflective practice cycle. Write a discussion post in which you use Gibbs’ (1988) cycle to analyze your second teaching/facilitation experience.

### Rubric {.unnumbered}

<table> <colgroup> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> </colgroup> <thead> <tr class="header"> <th><strong>Criteria</strong></th> <th><strong>Needs Improvement (0%)</strong></th> <th><strong>Developing</strong> <strong>(70%)</strong></th> <th><strong>Proficient</strong> <strong>(80%)</strong></th> <th><strong>Exemplary (100%)</strong></th> </tr> </thead> <tbody> <tr class="odd"> <td><strong>APA/Writing</strong></td> <td>Writing is not well organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.</td> <td>Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.</td> <td>Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.</td> <td>Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.</td> </tr> <tr class="even"> <td><strong>Developing a Cohesive and Logical Academic argument</strong></td> <td>Does not make a focused, cohesive, or logical academic argument. Posts and responses are confusing, and is missing an introduction, body, or conclusion. Transitions between sections and ideas are missing.</td> <td>Makes an academic argument that is only partially focused, cohesive and logical. Posts and responses are generally organized, but are missing an introduction, body, or conclusion. Transitions between sections and ideas are unclear.</td> <td>Makes a focused, cohesive, logical academic argument. Posts and responses are effectively organized and include an introduction, body, and conclusion. Transitions between sections and ideas are clear.</td> <td>Makes a focused, cohesive, logical and compelling academic argument. Posts and responses are effectively organized and include an introduction, body, and conclusion. Transitions between sections and ideas are clear, and build on each other.</td> </tr> <tr class="odd"> <td><strong>Interview Synopsis and Analysis</strong></td> <td>Does not include a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Does not include an analysis.</td> <td>Lists but does not discuss key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a partial analysis.</td> <td>Includes a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a thoughtful analysis.</td> <td>Includes a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a thoughtful analysis, integrating scholarly literature to support analysis and furthering scholarly thinking related to inclusive learning environments.</td> </tr> <tr class="even"> <td><strong>Scholarly Integration</strong></td> <td>Does not integrate references to support claims and assertions made in the paper.</td> <td>Integrates references to support some of the claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.</td> </tr> <tr class="odd"> <td></td> <td><strong>Needs Improvement (0%)</strong></td> <td><strong>Developing</strong> <strong>(70%)</strong></td> <td><strong>Proficient</strong> <strong>(80%)</strong></td> <td><strong>Exemplary (100%)</strong></td> </tr> </tbody> </table>

## Discussion 10: Reflective Practice – Facilitation 3

### Instructions {.unnumbered}

Review Unit 2 for an overview of Gibb’s (1988) reflective practice cycle. Write a discussion post in which you use Gibbs’ (1988) cycle to analyze your third teaching/facilitation experience.

### Rubric {.unnumbered}

<table> <colgroup> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> </colgroup> <thead> <tr class="header"> <th><strong>Criteria</strong></th> <th><strong>Needs Improvement (0%)</strong></th> <th><strong>Developing</strong> <strong>(70%)</strong></th> <th><strong>Proficient</strong> <strong>(80%)</strong></th> <th><strong>Exemplary (100%)</strong></th> </tr> </thead> <tbody> <tr class="odd"> <td><strong>APA/Writing</strong></td> <td>Writing is not well organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.</td> <td>Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.</td> <td>Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.</td> <td>Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.</td> </tr> <tr class="even"> <td><strong>Developing a Cohesive and Logical Academic argument</strong></td> <td>Does not make a focused, cohesive, or logical academic argument. Posts and responses are confusing, and is missing an introduction, body, or conclusion. Transitions between sections and ideas are missing.</td> <td>Makes an academic argument that is only partially focused, cohesive and logical. Posts and responses are generally organized, but are missing an introduction, body, or conclusion. Transitions between sections and ideas are unclear.</td> <td>Makes a focused, cohesive, logical academic argument. Posts and responses are effectively organized and include an introduction, body, and conclusion. Transitions between sections and ideas are clear.</td> <td>Makes a focused, cohesive, logical and compelling academic argument. Posts and responses are effectively organized and include an introduction, body, and conclusion. Transitions between sections and ideas are clear, and build on each other.</td> </tr> <tr class="odd"> <td><strong>Interview Synopsis and Analysis</strong></td> <td>Does not include a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Does not include an analysis.</td> <td>Lists but does not discuss key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a partial analysis.</td> <td>Includes a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a thoughtful analysis.</td> <td>Includes a detailed discussion of key elements of a culturally-inclusive learning community, including the physical environment, teacher/student relationships, and key aspects of the community. Includes a thoughtful analysis, integrating scholarly literature to support analysis and furthering scholarly thinking related to inclusive learning environments.</td> </tr> <tr class="even"> <td><strong>Scholarly Integration</strong></td> <td>Does not integrate references to support claims and assertions made in the paper.</td> <td>Integrates references to support some of the claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.</td> </tr> <tr class="odd"> <td></td> <td><strong>Needs Improvement (0%)</strong></td> <td><strong>Developing</strong> <strong>(70%)</strong></td> <td><strong>Proficient</strong> <strong>(80%)</strong></td> <td><strong>Exemplary (100%)</strong></td> </tr> </tbody> </table> -->
