# Summative Reflective Practice

## Overview {.unnumbered}

In Unit 6, our final unit, we will focus on synthesizing your professional experience in this practicum, completing the reflective practice cycle by reflecting on your learning throughout the practicum. By now, in this practicum, you have completed a minimum of 10 hours of classroom observation, designed three lesson plans, and facilitated three lessons. Teaching and facilitating is a deeply personal endeavor, and through this practicum you have challenged yourself to experiment with new facilitation skills, bravely taken on the role of facilitator, and pushed yourself to try new ways of creating authentic and meaningful learning experiences for students. As you prepare for this final reflection on your development and growth as a facilitator, you may want to take a few moments to reflect on the following questions:

- Having completed your classroom observation, lesson plan design, and facilitation, in what ways do you feel differently about teaching or facilitating?
- Do you think you are better prepared for a solo facilitation experience? Or perhaps more aware of how much you still need to learn?
- In what ways have you seen the principles of communities of learning reflected in your own teaching/facilitating practice?
- In what ways do you feel better equipped to teach in a cultural environment different from your own – or teach learners from a different culture?
- What do you consider to be the value of integrating adult learning theory into your role as a teacher/facilitator?

Throughout this practicum, you have begun gathering materials (classroom observation notes, lesson plans, etc.) that will be included in your Practicum Portfolio. These materials will be foundational to this reflective practice experience – and to the Practicum Portfolio you will compile in this unit.

### Topics {.unnumbered}

In this unit, we will focus on creating a:

1. Reflective Practice Practicum Portfolio

### Learning Outcomes {.unnumbered}

In this unit, you will engage in a summative reflective practice of your practicum experience. By the end of this unit, you should be able to:

- analyze your practicum experience using Gibbs’ [-@Gibbs1988] Reflective cycle.
- discuss how your personal philosophy of your role as teacher/facilitator influenced the learning community.
- assess your achievement of the learning goals you set at the beginning of your practicum.

### Learning Activities {.unnumbered}

::: {.learning-activity}

- Prepare and complete your final assignment: Reflective Practice Portfolio.

:::

### Assessment {.unnumbered}

The assessment for this unit includes your reflective practice practicum portfolio based on Gibbs’ [-@Gibbs1988] reflective cycle. This will be your final assignment for this course.

See the Assessment section in Moodle for more details.

## Preparing a Reflective Practice Practicum Portfolio

Throughout your practicum experience, you will continue to engage in reflective practice. In this unit, you will engage in your final reflective practice experience in this course – preparing a portfolio that demonstrates your learning in this course. While ideally you will take the practice of professional reflection with you into your future teaching/facilitating roles, in your Practicum Portfolio, you will document your completion of the required practicum elements (Observation, Lesson Plan Design, and Teaching/Facilitation), and reflect on your learning in the practicum experience.

## Summary {.unnumbered}

Completing your final assignment, the Reflective Practice Practicum Portfolio, marks the end of your journey in this course. Congratulations on reaching this milestone! I hope your practicum provided a valuable opportunity to apply your knowledge in a real-world environment and helped you realize how reflective practice can be beneficial as you seek to continually expand your expertise in teaching and facilitation. As you move forward in your career—whether as a teacher, facilitator, or in another creative role—I hope you continue to apply everything you’ve accomplished here. Well done!

::: {.check}

- Synthesize adult learning theory with practical experience facilitating or teaching
- Design authentic and inclusive learning experiences
- Demonstrate effective teaching/facilitation skills to support critical and creative thinking
- Integrate cross-cultural competency into the teaching/learning process
- Apply assessment strategies to measure student learning
- Synthesize personal identity, values, and beliefs into the facilitation and teaching process
- Engage in reflective practice within a facilitation/teaching role

:::

<!-- ## Assignment 5: Reflective Practice Practicum Portfolio

### Instructions {.unnumbered}

Upon completion of the 20 practicum hours, you will prepare a Reflective Practice Practicum Portfolio (15-20 pages) that synthesizes the practicum experience with current literature and prior knowledge. Your portfolio will include the Classroom Observation Logs, Facilitation Log, and Verification of Hours, as well as Lesson Plans you designed during the practicum. You will also include new writing, in which you synthesize your learning in this practicum, drawing on the reflections you posted in your reflective practice discussions. Finally, you will evaluate and analyze your learning in the practicum experience, considering the learning outcomes you set for yourself at the beginning of the practicum.

As you write your paper, be sure to use APA format. You will draw on Gibbs’ (1988) Reflective Cycle as you reflect on your learning and growth as a facilitator

Your paper should include the following sections:

1. Title Page
2. Table of Contents
3. Introduction and Practicum Learning Outcomes (1-2 pages)
4. Description. In this section, you will succinctly describe your practicum experience (1 page). As part of this section, provide the following evidence of 7our facilitation practice
    - Classroom Observation Log, Facilitation Log, and Verification of Hours (1 page)
    - Lesson Plan 1 (2-3 pages)
    - Lesson Plan 2 (2-3 pages)
    - Lesson Plan 3 (2-3 pages)
1. Feelings (1-2 pages)
2. Evaluation (1-2 pages)
3. Analysis (1-2 pages)
4. Conclusion and Action Plan (1-2 pages)
5. Reference List

### Rubric {.unnumbered}

<table> <colgroup> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> <col style="width: 20%" /> </colgroup> <thead> <tr class="header"> <th><strong>Criteria</strong></th> <th><strong>Needs Improvement (0%)</strong></th> <th><strong>Developing</strong> <strong>(70%)</strong></th> <th><strong>Proficient</strong> <strong>(80%)</strong></th> <th><strong>Exemplary (100%)</strong></th> </tr> </thead> <tbody> <tr class="odd"> <td><strong>Introduction (10%)</strong></td> <td>Does not include an introduction to the practicum portfolio. Does not list the practicum learning outcomes.</td> <td>Includes an introduction to the practicum portfolio or lists some of the practicum learning outcomes.</td> <td>Includes an introduction to the practicum portfolio. Lists each of the practicum learning outcomes.</td> <td>Includes an introduction to the practicum portfolio, with an explanation of Gibb’s (1988) Reflective Practice Model. Lists each of the practicum learning outcomes, and includes an explanation of how specific elements of the portfolio demonstrate achievement of learning outcomes.</td> </tr> <tr class="even"> <td><strong>Description (15%)</strong></td> <td>Does not include a description of the practicum experience. Does not include three Lesson Plans.</td> <td>Does not include a description of the practicum experience. Does not include three Lesson Plans.</td> <td>Includes a description of the practicum experience. Includes three Lesson Plans.</td> <td>Includes an insightful description of the practicum experience, integrating scholarly sources to support description. Includes three Lesson Plans.</td> </tr> <tr class="odd"> <td><strong>Feelings (15%)</strong></td> <td>Does not include an analysis of feelings related to the practicum experience. Does not include a discussion of how students may have felt during and about the learning activities.</td> <td>Includes an analysis of feelings related to the practicum experience, including some (but not all) of the following: feelings before, during, and after the classroom observation, lesson plan design, and facilitation and/or includes a discussion of how students may have felt during and about the learning activities.</td> <td>Includes an analysis of feelings related to the practicum experience, including feelings before, during, and after the classroom observation, lesson plan design, and facilitation. Includes a discussion of how students may have felt during and about the learning activities. e.</td> <td>Includes an analysis of feelings related to the practicum experience, including feelings before, during, and after the classroom observation, lesson plan design, and facilitation. Includes a discussion of how students may have felt during and about the learning activities. Includes a summative analysis of feelings about the practicum as a whole.</td> </tr> <tr class="even"> <td><strong>Evaluation (15%)</strong></td> <td>Does not include an evaluation of all elements of the practicum experience: classroom observation, lesson plan design, and facilitation. The evaluation does not include a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.</td> <td>Includes an evaluation of some (but not all) of the following: classroom observation, lesson plan design, and facilitation. The evaluation includes a description of some of the following: what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.</td> <td>Includes an evaluation of the practicum experience, including classroom observation, lesson plan design, and facilitation. The evaluation includes a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.</td> <td>Includes an evaluation of the practicum experience, including classroom observation, lesson plan design, and facilitation, with references to the literature related to Gibbs’ Reflective Practice and/or other scholarly sources. The evaluation includes a description of what went well, what did not go well, and how students or facilitator contributed to the success of the experience. Incorporates references to scholarly literature to support evaluation.</td> </tr> <tr class="odd"> <td><strong>Analysis (15%)</strong></td> <td>Does not include an analysis of all elements of the practicum experience: classroom observation, lesson plan design, and facilitation. Does not include an analysis of all the following: why things went well, why things didn’t go well, and the meaning of this experience. Does not incorporate other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis. Does not list personal practicum learning outcomes or a discussion of how each practicum learning outcome was achieved.</td> <td>Includes an analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation. Includes an incomplete analysis of some of the following: why things went well, why things didn’t go well, and the meaning of this experience. Minimally incorporates other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis. Includes a list of personal practicum learning outcomes and a discussion of how some of the practicum learning outcomes were achieved.</td> <td>Includes an analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation. Includes an analysis of why things went well, why things didn’t go well, and the meaning of this experience. Incorporates other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis. Includes a list of personal practicum learning outcomes and a discussion of how each practicum learning outcome was achieved.</td> <td>Includes an insightful analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation. Includes an insightful analysis of why things went well, why things didn’t go well, and the meaning of this experience. Includes a list of personal practicum learning outcomes and a discussion of how each practicum learning outcome was achieved.</td> </tr> <tr class="even"> <td><strong>Developing a Cohesive and Logical Academic argument (10%)</strong></td> <td>Does not make a focused, cohesive, or logical academic argument. Portfolio is not well organized and/or is missing some of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are missing.</td> <td>Makes an academic argument that is only partially focused, cohesive and logical. Portfolio is generally organized but is missing some of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are unclear.</td> <td>Makes a focused, cohesive, logical academic argument. Portfolios effectively organized and includes all of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are clear.</td> <td>Makes a focused, cohesive, logical, and compelling academic argument. Portfolio is effectively organized and includes all of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are clear and build on each other.</td> </tr> <tr class="odd"> <td><strong>Scholarly Integration (10%)</strong></td> <td>Does not integrate references to support claims and assertions made in the paper.</td> <td>Integrates references to support some of the claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper.</td> <td>Integrates references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.</td> </tr> <tr class="even"> <td><strong>APA/Writing (10%)</strong></td> <td>Paper does not model language and conventions used in scholarly literature. Writing is not well organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.</td> <td>Paper partially models language and conventions used in scholarly literature. Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.</td> <td>Paper consistently models language and conventions used in scholarly literature. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.</td> <td>Paper is an exemplar of language and conventions used in scholarly literature. Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.</td> </tr> <tr class="odd"> <td></td> <td><strong>Needs Improvement (0%)</strong></td> <td><strong>Developing</strong> <strong>(70%)</strong></td> <td><strong>Proficient</strong> <strong>(80%)</strong></td> <td><strong>Exemplary (100%)</strong></td> </tr> </tbody> </table> -->
