# Pre-work: Practicum Proposal {.unnumbered}

## Overview {.unnumbered}

Welcome to LDRS 667 Practicum: Personal and Professional Practice and Reflection. In this unit (pre-work), you will prepare for your practicum in coaching and facilitation in a professional learning setting.

As you prepare to engage in your practicum, you will complete pre-work that includes preparing and submitting a Practicum Proposal for review by your instructor, and reviewing materials from previous courses.

This course provides students with a practical setting in which to apply what they have learned in the Certificate in Coaching and Facilitation. Using reflective practice, learners apply learning theory, assessment theory, facilitation practices, and cross-cultural competency, in a professional learning facilitation setting. The practicum must be with a supervised business, non-profit agency, social service agency, or institution related to the student’s personal interests and future plans.

### Topics {.unnumbered}

In this unit, we will focus on two topics:

1. Writing your Practicum Proposal
2. Preparation for Teaching/Facilitating

### Learning Outcomes {.unnumbered}

When you have completed this pre-work, you should be able to:

1. Formulate personal learning outcomes for the practicum experience.
2. Synthesize personal identity, values, and beliefs with personal learning outcomes for practicum experience.

### Activity Checklist {.unnumbered}

Here is a checklist of learning activities you will benefit from in completing this unit. You may find it useful for planning your work.

::: {.note}

**Learning Activities**

- Select a practicum site, in preparation for your practicum.
- Re-read: Palmer, P.J. (2017). The courage to teach: Exploring the inner landscape of a teacher's life. Hoboken, NJ: Jossey-Bass. Re-read: Introduction, Ch 1: The Heart of a Teacher, Ch 3: The Hidden Wholeness: Paradox in Teaching and Learning, as well as other readers to prepare yourself for the practicum.
- If you need a refresher on how to write Learning Outcomes for your Practicum, read:[Learning outcomes; course/curriculum design.](https://teaching.uwo.ca/curriculum/coursedesign/learning-outcomes.html){target="_blank"}
- Review your Reflective Journal from previous courses (e.g. LDRS 627).

:::

::: {.note}

**Assessment**

- Assignment: Practicum Proposal: In preparation for the Practicum, write and submit your Practicum Proposal to your Professor (includes practicum site and signed mentor agreement).

:::

## Practicum Proposal

In this practicum, you will engage in rich, experiential learning, deepening your skills in teaching/facilitation and applying scholarly learning from previous courses within a practical setting. To prepare for this experience, you will create a Practicum Proposal.

### Activity: Select a Practicum Site

::: {.learning-activity}

In preparation for completing your Practicum Proposal, identify a practicum site. You may already have a practicum site in mind. If not, be sure to select a site that will provide you with an opportunity to practice your skills in teaching/facilitation. You will also need to secure a mentor at that site, who will be your practicum site contact, provide you feedback on your teaching/facilitation, and sign off on completion of classroom observation and teaching/facilitation hours.

:::

## Preparation for Teaching/facilitating

As you prepare for your practicum experience, now is a great time to review materials you have previously studied in your graduate studies. As you consider these materials, begin to think about the nature of the learning environment you want to create, and the learning experiences you imagine for your students. This is a great time to dive into some of the books, articles, and videos you studied in previous courses and have wanted to read/view again.

### Activity: Preparation for Practicum

::: {.learning-activity}

1. Re-read: Palmer, P.J. (2017). The courage to teach: Exploring the inner landscape of a teacher's life. Hoboken, NJ: Jossey-Bass. Re-red: Introduction, Ch 1: The Heart of a Teacher, Ch 3: The Hidden Wholeness: Paradox in Teaching and Learning), as well as other readers to prepare yourself for the practicum
2. If you need a refresher on how to write Learning Outcomes for your Practicum, read: [Learning Outcomes](https://teaching.uwo.ca/curriculum/coursedesign/learning-outcomes.html){target="_blank"}
3. Review prior course materials to prepare you for engagement in this practicum experience.
4. Review your Reflective Journal from previous classes.

:::

## Assessment {.unnumbered}

**Practicum Proposal (10%)**

After identifying a practicum site, write a 3-5 page Practicum Proposal, including the following sections:

1. Practicum Site: Include a description of the context in which you will conduct your practicum. Although you need to identify your site for this assignment, you should consider whether you want to keep the site anonymous for your discussions in the Practicum Course. If so, be sure to indicate in your proposal how you will avoid identifying details in course discussions.
2. Practicum Mentor: Include the signed [Mentor Agreement](assets/u0/LDRS_667_Mentor_Agreement.pdf){target="_blank"}.
3. Learning Outcomes: Include three personal professional learning outcomes that will shape your experiential learning in this practicum. What do you want to learn during the practicum experience?
4. Planned Schedule for 20 Hours of Experiential Learning, to include:
    1. Observation of Teaching (Minimum of 10 hours)
    2. Designing and Facilitating Lessons/Classes (Minimum of 10 hours, Minimum of 3 Lessons)
    3. Facilitating Online or Face-to-Face Discussions
5. Learning: An analysis of how this practicum will contribute to the achievement of practicum learning outcomes. Be specific.
6. Career Planning: A discussion of how this practicum will build on your current academic, personal, and professional knowledge, and how it will contribute to your career goals. Be specific.

The Practicum Proposal should be written in APA format.

**Assignment Submission**

Submit your Practicum Proposal in the folder in Moodle for your instructor to review. The Practicum Proposal is due prior to the start of the Practicum course, usually 1-2 weeks in advance. (Review the Due Dates tab for exact date).

The Practicum Proposal is worth 10% of your course grade.

This is a required assignment. You cannot begin any onsite or online elements of this course until you receive approval form your professor.

::: {.accordion title="Rubric: Practicum Proposal (Click to expand)"}

| |Unsatisfactory 0% |Developing 50% (C)|Proficient 75% (B)|Exemplary 100% (A)|
|--- |--- |--- |--- |--- |
| **Practicum site (10%)** | Does not includes a description of the context in which the practicum will be conducted. If the site will be anonymous to other learner, does not include a plan for how identifying details will be avoided in course discussions. Does not include a signed mentor agreement. | Includes an incomplete description of the context in which the practicum will be conducted. If the site will be anonymous to other learner, includes an incomplete plan for how identifying details will be avoided in course discussions. Note: A mentor agreement is included but is incomplete. | Includes a description of the context in which the practicum will be conducted. If the site will be anonymous to other learner, includes a plan for how identifying details will be avoided in course discussions. Note: A signed mentor agreement is required before the practicum can begin. | Includes a description of the context in which the practicum will be conducted, including an analysis of the learning environment. If the site will be anonymous to other learner, includes a plan for how identifying details will be avoided in course discussions. Note: A signed mentor agreement is required before the practicum can begin. | | |
| **PRACTICUM Learning Outcome(s) (20%)** | Does not include three learning outcomes for the practicum clearly align with program learning outcomes. LOs are not at an appropriate level for graduate-level practicum. The LOs do not begin with “At the completion of this practicum, I will be able to…”, and/or do not include one learning verb (apply, analyze, etc.) and/or one noun (what students will learn). | The learning outcomes for the practicum do not clearly align with program learning outcomes. LOs are at close to being at appropriate level for graduate-level practicum. The LOs do not begin with “At the completion of this practicum, I will be able to…”, and/or includes more than/less than one learning verb (apply, analyze, etc.) and more than/less than one noun (what students will learn). | The learning outcomes for the practicum align with program learning outcomes. Learning outcomes are at an appropriate level for a graduate-level practicum. The LOs begin with “At the completion of this practicum, I will be able to…”, and include one learning verb (apply, analyze, etc.) and one noun (what students will learn). | The learning outcomes for the practicum clearly align with program learning outcomes. LOs are at an appropriate level for graduate-level practicum and will expand the expertise of the practicum student. The LOs begin with “At the completion of this practicum, I will be able to…”, and includes one learning verb (apply, analyze, etc.) and one noun (what students will learn). | | |
| **SCHEDULE FOR EXPERIENTIAL LEARNING (10%)** | Does not includes a plan to achieve the requirements of a minimum of 10 hours of classroom observation, and 10 hours of curriculum design and facilitation. | Includes a vague plan to achieve the requirements, but does not specifically include a plan for a minimum of 10 hours of classroom observation, and/or 10 hours of curriculum design and facilitation. | Includes a specific plan to achieve the requirements of a minimum of 10 hours of classroom observation, and 10 hours of curriculum design and facilitation. | Includes a specific plan to achieve the requirements of a minimum of 10 hours of classroom observation, and 10 hours of curriculum design and facilitation, including specific dates/times. | | |
| **ACHIEVEMENT OF PRACTICUM LEARNING OUTCOMES (20%)** | Does not includes an analysis of how the practicum will contribute to achievement of practicum learning outcomes. | Includes a vague description of how this practicum will contribute to achievement of practicum learning outcomes, or does not address all learning outcomes. | Includes an analysis of how this practicum will contribute to achievement of practicum learning outcomes. | Includes an insightful analysis of how this practicum will contribute to achievement of practicum learning outcomes, integrating scholarly sources to support this analysis. | | |
| **CAREER PREPARATION (10%)** | Does not includes a discussion of how this practicum will build on student’s current academic, personal, and professional knowledge. Does not include an explanation of how it will contribute to career goals. | Includes a partial discussion of how this practicum will build on student’s current academic, personal, and professional knowledge OR includes a partial explanation of how it will contribute to career goals. | Includes a discussion of how this practicum will build on student’s current academic, personal, and professional knowledge. Includes an explanation of how it will contribute to career goals. | Includes an analysis of how this practicum will build on student’s current academic, personal, and professional knowledge. Includes an explanation of how it will contribute to career goals. Includes references to scholarly, peer-reviewed resources to support this analysis. | | |
| **APA/Writing (10%)** | The practicum proposal does not follows the proposal guidelines and/or writing is not well-organized and includes several errors in grammar or composition and/or some resources are not appropriately cited using APA format. | The practicum proposal follows some of the proposal guidelines. Writing is somewhat organized and includes a few errors in grammar or composition. All resources are cited, but there are some errors in APA format. | The practicum proposal follows the template. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited using APA format. | The practicum proposal follows the template. Writing is well-organized and includes no errors in grammar or composition. All resources are appropriately cited using APA format. | | |
| **POSSIBLE POINTS** | 0 | 50 | 75 | 100 | | |

:::

## Pre-work Summary

In this pre-work, you have prepared for your practicum experience by developing a Practicum Proposal, and reviewing prior course materials.

## Checking Your Learning {.unnumbered}

::: {.check}

As you prepare to launch your practicum experience, you may want to check to make sure that you are able to:

- Formulate personal learning outcomes for the practicum experience.
- Synthesize personal identity, values, and beliefs with personal learning outcomes for practicum experience.

:::

## References {.unnumbered}

- Palmer, P.J. (2017). The courage to teach: Exploring the inner landscape of a teacher's life. Hoboken, NJ: Jossey-Bass.
- Queens University Center for Teaching and Learning. (n.d.) “Learning outcomes; course/curriculum design.” Retrieved from: [www.queensu.ca/ctl/teaching-support/course-and-program-design](http://www.queensu.ca/ctl/teaching-support/course-and-program-design){target="_blank"}

::: {.prote}

Above link is dead

:::
