# Summative Reflective Practice

## Overview {-}

In Unit 5, our final unit, we will focus on synthesizing your professional experience in this practicum, completing a summative reflective analysis of your learning. In this practicum, you have completed a minimum of 10 hours of classroom observation, designed three lesson plans, and facilitated three lesson. As you prepare for this final reflection on your development as a teacher/facilitator, you may want to take a few moments to reflect on the following questions:

1. Having completed your classroom observation, lesson plan design, and facilitation, do you feel differently about teaching?  
2. Do you think you are better prepared for a solo teaching experience? Or perhaps more aware of how much you still need to learn?  
3. Have you seen the principles of communities of learning reflected in your own teaching/facilitating experience?  
4. In what ways do you feel better equipped to teach in a cultural environment different from your own?  
5. What do you consider to be the value of integrating adult learning theory into your role as a teacher/facilitator?  

Throughout this practicum, you have begun gathering materials (classroom observation notes, lesson plans, etc.) that will be included in your Practicum Portfolio. These materials will be foundational to this reflective practice experience – and to the Practicum Portfolio you will compile in this unit.

### Topics {-}

In this unit, we will focus on creating a:

1. Reflective Practice Practicum Portfolio  


### Learning Outcomes {-}

In this unit, you will engage in a summative reflective practice of your practicum experience. By the end of this unit, you should be able to:

- Analyze your practicum experience using Gibbs' (1988) Reflective cycle.  
- Discuss how your personal philosophy of your role as teacher/facilitator influenced the learning community.  
- Assess your achievement of the learning goals you set at the beginning of your practicum.  

### Activity Checklist {-}

This unit includes one activity: the preparation of a Reflective Practice Practicum Portfolio.

```{block2, type='assessment'}

<span class="blockhead">Assessment</span> 

- Complete your Reflective Practice Practicum Portfolio based on Gibbs' (1988) Reflective Cycle. See assignment instruction for details. The portfolio includes the following:  
  - Classroom Observation Log  
  - Lesson Plan Design Log  
  - Teaching Facilitation Log  
  - Verification of Hours (signed by mentor)  

```

## Preparing a Reflective Practice Practicum Portfolio

In this unit, you will engage in your final reflective practice experience in this course – preparing a portfolio that demonstrates your learning in this course. While ideally you will take the practice of professional reflection with you into your future teaching/facilitating roles, in this unit you will synthesize your learning in this course, by preparing the Practicum Portfolio.

## Unit Summary {-}

Throughout your practicum experience, you have engaged in reflective practice. In this final unit, you have synthesized your learning in a summative Reflective Practice Practicum Portfolio, demonstrating how you have applied your learning in a teaching/facilitation role.

## Assessment {-}

```{block2, type='assessment'}

<span class="blockhead">Reflective Practice Practicum Portfolio</span>

Upon completion of the 20 practicum hours, learners will prepare a Reflective Practice Portfolio (15-20 pages) that synthesizes the practicum experience with current literature and prior knowledge. This portfolio will include the Classroom Observation Logs, Facilitation Log, and Verification of Hours, as well as Lesson Plans designed during the practicum. It will also include new writing, which will synthesize the reflective practice discussions, and include summative evaluation and analysis of learning in the practicum experience.

This paper will be written using APA format and will be based on Gibbs' (1988) Reflective Cycle. The paper will include the following sections:

1. Title Page  
2. Table of Contents  
3. Introduction and Practicum Learning Outcomes (1-2 pages)  
4. Description:  
  - Classroom Observation Log, Facilitation Log, and Verification of Hours (1 page)  
  - Lesson Plan 1 (2-3 pages)  
  - Lesson Plan 2 (2-3 pages)  
  - Lesson Plan 3 (2-3 pages)  
5. Feelings (1-2 pages)  
6. Evaluation (1-2 pages)  
7. Analysis (1-2 pages)  
8. Conclusion and Action Plan (1-2 pages)  
9. Reference List  

<details><summary>**RUBRIC: Reflective Practice Practicum Portfolio (Click to expand)**</summary>

|                                                          | UNSATISFACTORY                                                                                                                                                                                                                                                                                                           | DEVELOPING                                                                                                                                                                                                                                                                                                                                                                                                   | PROFICIENT                                                                                                                                                                                                                                                                                                                                                   | EXEMPLARY                                                                                                                                                                                                                                                                                                                                                   |
|-----------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | 0%                                                                                                                                                                                                                                                                                                                       | 50% (C)                                                                                                                                                                                                                                                                                                                                                                                                      | 75% (B)                                                                                                                                                                                                                                                                                                                                                      | 100% (A)                                                                                                                                                                                                                                                                                                                                                    |
| INTRODUCTION (10%)                                        | Does not includes an introduction to the practicum portfolio. Does not list the practicum learning outcomes.                                                                                                                                                                                                             | Includes an introduction to the practicum portfolio or lists some or none of the practicum learning outcomes.                                                                                                                                                                                                                                                                                                | *Includes an introduction to the practicum portfolio. Lists each of the practicum learning outcomes.*                                                                                                                                                                                                                                                        | Includes an introduction to the practicum portfolio, Gibb’s (1988) Reflective Practice Model. Lists each of the practicum learning outcomes, and includes an explanation of how specific elements of the portfolio demonstrate achievement of learning outcomes.                                                                                            |
| DESCRIPTION (15%)                                         | Does not include a description of the practicum experience.                                                                                                                                                                                                                                                              | Does not include a description of the practicum experience.                                                                                                                                                                                                                                                                                                                                                  | *Includes a description of the practicum experience. *                                                                                                                                                                                                                                                                                                       | Includes an insightful description of the practicum experience, integrating scholarly sources to support description.                                                                                                                                                                                                                                       |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not include Classroom Observation Log, Facilitation Log, and/or Verification of Hours. (Note: These are all required to pass the Practicum).                                                                                                                                                                        | Includes some, but not all of the following: Classroom Observation Log, Facilitation Log, and/or Verification of Hours. (Note: These are all required to pass the Practicum).                                                                                                                                                                                                                                | *Includes all of the following: Classroom Observation Log, Facilitation Log, and Verification of Hours. (Note: These are all required to pass the Practicum).*                                                                                                                                                                                               | Includes all of the following: Classroom Observation Log, Facilitation Log, and Verification of Hours. (Note: These are all required to pass the Practicum).                                                                                                                                                                                                |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not includes three Lesson Plans.                                                                                                                                                                                                                                                                                    | Does not includes three Lesson Plans.                                                                                                                                                                                                                                                                                                                                                                        | *Includes three Lesson Plans.*                                                                                                                                                                                                                                                                                                                               | Includes three Lesson Plans                                                                                                                                                                                                                                                                                                                                 |
| FEELINGS (15%)                                            | Does not include an analysis of feelings related to the practicum experience. Does not include a discussion of how students may have felt during and about the learning activities. Does not include a summative analysis of feelings about the practicum as a whole.                                                    | Includes an analysis of feelings related to the practicum experience, including some (but not all) of the following: feelings before, during, and after the classroom observation, lesson plan design, and facilitation and/or includes a discussion of how students may have felt during and about the learning activities and/or includes a summative analysis of feelings about the practicum as a whole. | *Includes an analysis of feelings related to the practicum experience, including feelings before, during, and after the classroom observation, lesson plan design, and facilitation. Includes a discussion of how students may have felt during and about the learning activities Includes a summative analysis of feelings about the practicum as a whole.* | Includes an analysis of feelings related to the practicum experience, including feelings before, during, and after the classroom observation, lesson plan design, and facilitation. Includes a discussion of how students may have felt during and about the learning activities Includes a summative analysis of feelings about the practicum as a whole.  |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              | The analysis includes references to the literature related to Gibb’s Reflective Practice and/or other scholarly sources.                                                                                                                                                                                                                                    |
| EVALUATION (15%)                                          | Does not include an evaluation of all elements of the practicum experience: classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                 | Includes an evaluation of one or more parts of the practicum experience: classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                                                        | *Includes an evaluation of the practicum experience, including classroom observation, lesson plan design, and facilitation. *                                                                                                                                                                                                                                | Includes an evaluation of the practicum experience, including classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                  |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | The evaluation does not include a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.                                                                                                                                                      | The evaluation includes a description of some of the following: what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.                                                                                                                                                                                                                           | *The evaluation includes a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.*                                                                                                                                                                                                | The evaluation includes a description of what went well, what didn’t go well, and how students or facilitator contributed to the success of the experience.                                                                                                                                                                                                 |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              | Incorporates references to scholarly literature to support evaluation.                                                                                                                                                                                                                                                                                      |
| ANALYSIS (15%)                                            | Does not include an analysis of all elements of the practicum experience: classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                   | Includes an analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation.                                                                                                                                                                                                                                                                                     | *Includes an analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation. *                                                                                                                                                                                                                                  | *Includes an insightful analysis of the practicum experience, including classroom observation, lesson plan design, and facilitation. *                                                                                                                                                                                                                      |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not include an analysis of all the following: why things went well, why things didn’t go well, and the meaning of this experience. Does not incorporate other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis.                                                | Includes an incomplete analysis of some of the following: why things went well, why things didn’t go well, and the meaning of this experience. Minimally incorporates other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis.                                                                                                                           | *Includes an analysis of why things went well, why things didn’t go well, and the meaning of this experience. Incorporates other resources (including scholarly sources, practicum feedback, and discussion feedback) in this analysis. *                                                                                                                    | *Includes an insightful analysis of why things went well, why things didn’t go well, and the meaning of this experience.*                                                                                                                                                                                                                                   |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           | Does not include a discussion of how each practicum learning outcome was achieved.                                                                                                                                                                                                                                       | Includes a discussion of how some of the practicum learning outcome were achieved.                                                                                                                                                                                                                                                                                                                           | *Includes a discussion of how each practicum learning outcome was achieved.*                                                                                                                                                                                                                                                                                 | *Synthesizes the analysis with other resources (including scholarly sources, practicum feedback, and discussion feedback).*                                                                                                                                                                                                                                 |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                             |
|                                                           |                                                                                                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                              | *Synthesize personal identity, values, and beliefs into the facilitation and teaching process*                                                                                                                                                                                                                                                               | *Includes a discussion of how each practicum learning outcome was achieved.*                                                                                                                                                                                                                                                                                |
| DEVELOPING A COHESIVE AND LOGICAL ACADEMIC ARGUMENT (10%) | Does not make a focused, cohesive, or logical academic argument. Paper is confusing, and is missing some of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are missing. | Makes an academic argument that is only partially focused, cohesive and logical. Paper is generally organized but is missing some of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are unclear.                                                            | *Makes a focused, cohesive, logical academic argument. Paper is effectively organized and includes all of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are clear. *                                       | Makes a focused, cohesive, logical and compelling academic argument. Paper is effectively organized and includes all of the following: title page, table of contents, introduction, description, feelings, evaluation, analysis, conclusion and action plan, and reference list. Transitions between sections and ideas are clear, and build on each other. |
| SCHOLARLY INTEGRATION (10%)                               | Does not integrate references to support claims and assertions made in the paper.                                                                                                                                                                                                                                        | Integrates references to support some of the claims and assertions made in the paper.                                                                                                                                                                                                                                                                                                                        | *Integrates references to support claims and assertions made in the paper.*                                                                                                                                                                                                                                                                                  | Integrates references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.                                                                                                                                                                                      |
| APA/WRITING (10%)                                         | Paper does not model language and conventions used in scholarly literature. Writing is not well-organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.                                                                                               | Paper partially models language and conventions used in scholarly literature. Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.                                                                                                                                            | *Paper consistently models language and conventions used in scholarly literature. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.*                                             | Paper is an exemplar of language and conventions used in scholarly literature. Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.                                                                                                                                      |
| TOTAL                                                     | 0% (F)                                                                                                                                                                                                                                                                                                                   | 50% (C)                                                                                                                                                                                                                                                                                                                                                                                                      | 75% (B)                                                                                                                                                                                                                                                                                                                                                      | 100% (A+)                                                                                                                                                                                                                                                                                                                                                   |

</details>

See [here](assets/u5/LDRS_667_Portfolio_Rubric.pdf){target="_blank"} for grading rubric.

```

## Checking your Learning {-}

```{block2, type='progress'}

As you complete this final unit in the practicum, consider the learning outcomes for this practicum. Having completed the classroom observation, designing lesson plans, and teaching/facilitating, you should now be able to:

- Synthesize adult learning theory with practical experience facilitating or teaching  
- Design authentic and inclusive learning experiences  
- Demonstrate effective teaching/facilitation skills to support critical and creative thinking  
- Integrate cross-cultural competency into the teaching/learning process  
- Apply assessment strategies to measure student learning  
- Synthesize personal identity, values, and beliefs into the facilitation and teaching process  
- Engage in reflective practice within a facilitation/teaching role  

```
